Lesson4
Gaileks/LearnEnglishWordsTelegramBot pull request #4
Opened 2023-09-07 11:37 UTC by Gaileks

2023-09-09 11:44 UTC, danelyan requested changes
Накидал комментов. Что касается:

> Искал информацию, как изменить определенную строчку в файле, не нашел, конечно можно переписывать весь файл или работать с коллекцией, а  инфу в файле менять по запросу ( отдельная кнопка) или при завершении сеанса работы программы… но это все как то не то …

Давай для простоты переписывать файл целиком. При таком небольшом файле проблем не будет. В реальном проекте, правильнее было бы использовать InputStream и OutpuStream из JavaIO. Это интерфейсы, которые позволяют работать с файлом как с потоком байтов, "навигируясь" по нему.

Но еще более правильным решением было бы использовать базу данных. В нашем случае подошел бы SQLite (это по сути база из одного файла). Помимо того, что данные хранились бы эффективнее, исключались бы проблемы с ресурсами.

После 10 этапа курсовой, я предлагаю ряд доработок, на выбор студента, среди них есть внедрение базы.

Впрочем, если захочешь, можно и JavaIO применить, но давай после 10 этапа, к счастью часть по работе с файлом можно вынести отдельно и доработать позже.

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +        val menuItems = """
Это лучше вынести в константу. Чтобы не загромождать функцию. Ведь текст внутри статичен, и логики никакой не содержит.

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +        var number: Int?
Выглядит очень похожим на Java (что не всегда плохо).
Смущает две проверки на null, одна для вывода строки, вторая для решении об итерации цикла.

```Kotlin
fun checkingInput(): Int {
    var number: Int?
    do {
        number = readln().toIntOrNull()
        if (number == null) {
            println("Введенное значение не удовлетворяет требованиям".red())
        } else {
            return number
        }
    } while (true)
}
```

Но я бы сократил. Kotlin славится своими extension-функциями и elvis оператором:

```Kotlin
    while (true) {
        readln().toIntOrNull()
            ?.let { return it }
            ?: println("Введенное значение не удовлетворяет требованиям".red())
    }
```

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            getFourNotLearnedWord()
Тут название метода сбивает с толку - метод начинается с get..., но при этом ничего не возвращает, а загружает слова в переменную. Тогда уже `loadNotLearnedWords()`.

А еще в название метода захардкожено количество элементов. Давай вынесем 4 в константу, а методу дадим более универсальное имя

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +          1 - ${fourNotLearnedWord[0].translate}
learningMenu можно сформировать при помощи `fourNotLearnedWord.map {}`, попробуем?
Тогда, опять же, не будет привязки к 4 элементам.

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            if (it.correctAnswersCount < 3) notLearnedWord.add(it)
3 - претендент на вынесение в константы (или даже в параметры Learning)

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            //TODO Изменить количество правильных ответов (correctAnswersCount)
Да, давай сохранять весь список в файл, перезаписывая его

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/WordFile.kt
> +     val wordFile = File("words.txt")
лишний пробел

2023-09-09 11:44 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/extensions.kt
> +fun checkingInput(): Int {
Этих метода два. Наверное тот что выше в ConsoleMenu уже не нужен

2023-09-11 17:16 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +        var number: Int?
Ну да, я сначала немного Java изучал, теперь Kotlin  учу (Kotlin  , кстати, нравится больше ). 
Отличная конструкция, спасибо, вреде эти операторы изучал, все помню, а вот не применил же )))  Вот тут кстати вопрос, а как правильно( принято) переносить  строки ?

2023-09-12 11:24 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/WordFile.kt
> +     val wordFile = File("words.txt")
А где лишний пробел, у меня автоформат так правит,  если надо я его отредактирую

2023-09-14 05:42 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +        var number: Int?
Перенос строк как правило на усмотрение команды и строгих правил нет. Правила задают во всяких линтерах (например Detekt)

Мы переносим так как в моем примере, чтобы читалось:
- прочитай из консоли и конвертируй в Int если сможешь, не сможешь - в нуль
- возьми если не нуль и выйди из функции
- если нуль - напечатай

2023-09-14 05:47 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/WordFile.kt
> +     val wordFile = File("words.txt")
Было вот так, если в истории гита посмотреть, но видимо автоформат поправил сам )

<img width="495" alt="Screenshot 2023-09-14 at 08 45 34" src="https://github.com/Gaileks/LearnEnglishWordsTelegramBot/assets/7125622/545cf66b-6d4a-4434-9d65-f88eb79cf8c7">

2023-09-14 06:19 UTC, danelyan requested changes

2023-09-14 06:19 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +                    println("Спасио, что пользовались нашей программой".cyan())
опечатка

2023-09-14 06:19 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            println("Спасио, что пользовались нашей программой".cyan())
опечатка

2023-09-14 06:19 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            when (checkingInput()) {
тут можно сократить и сделать универсальнее:
```Kotlin
in 1..<fourNotLearnedWord.size -> ...
fourNotLearnedWord.size -> continue
fourNotLearnedWord.size + 1 -> ...
else ->
```

2023-09-14 06:19 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            val hiddenWord = notLearnedWord.shuffled()[0]
Бот неправильно работает, просит перевести слово, но среди вариантов нет правильного

2023-09-14 06:24 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            val hiddenWord = notLearnedWord.shuffled()[0]
а, и можно просто использовать метод random() вместо shuffled()[0]

2023-09-18 14:26 UTC, danelyan requested changes
Отлично. Но давай последний момент поправим

2023-09-18 14:26 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Learning.kt
> +            val hiddenWord = notLearnedWord.random()
давай упростим все-таки. Ты же можешь брать 4 невыученных слова (и меньше, если невыученных осталось меньше 4), а далее из этих невыученных выбрать одно рандомное, которое и будет показываться. Ну и далее дополнять до 4, опять же на случай если  невыученных меньше 4

2023-09-19 15:22 UTC, danelyan requested changes
Постарался подробнее описать, что смущает в твоем решении.
Это не критично, даже на грани "вкусовщины", так как решение в целом рабочее.
Но ты сам говорил, что ревью для тебя самое важное - получай :)

1. Создание объектов в цикле:

```Kotlin
while (true) {
    println(menuItems)
    when (checkingInput()) {
        1 -> Learning().startLearningMenu()
        2 -> Statistics().getStatisticsInfo()
        3 -> WordFile().resetProgress()
        0 -> {
            println("Спасибо, что пользовались нашей программой".cyan())
            exitProcess(0)
        }

        else -> println("Не корректный номер пункта меню".red())

    }
}
```

Отдельный класс, для каждого пункта меню - хорошо. 
Но желательно стремиться к переиспользованию. 

```Kotlin

val learning = Learning()
val statistics = Statistics()
val wordFile = WordFile()

while (true) {
    println(menuItems)
    when (checkingInput()) {
        1 -> learning.startLearningMenu()
        2 -> statistics.getStatisticsInfo()
        3 -> wordFile.resetProgress()
        0 -> {
            println("Спасибо, что пользовались нашей программой".cyan())
            exitProcess(0)
        }

        else -> println("Не корректный номер пункта меню".red())

    }
}
```

Всегда когда работаешь с циклом, задумывайся о создаваемых объектах.
Но, забегая вперед - **оставь эту логику как есть**, в следующем этапе мы сделаем один класс для работы с тренажером.

2. Старайся делать переменные немутабельными, насколько это возможно.
- К примеру, список notLearnedWord можно загружать сразу. 
- кстати, обрати внимание, вместо forEach можно использовать extension-функцию `filter()`.
- И старайся придерживаться единого стиля, при сортировке элементов в классе. Например: сначала все переменные, потом init{}, потом public методы, потом приватные. 

```Kotlin

class Learning {

    private val notLearnedWord = WordFile().dictionary
        .filter { it.correctAnswersCount < REPETITIONS_TO_MEMORIZE }
    
    private var fourNotLearnedWord: MutableList<Word> = mutableListOf()
    
    init {
        checkingLearnedWords()
    }


```

Впрочем, в пункте 3 мы избавимся от fourNotLearnedWord, так что переходи к 3

3. Стоит упростить логику выбора слов.

Давай проговорим алгоритм:
- Загрузить весь словарь
- Взять оттуда невыученные слова
- Из невыученных выбрать N случайных
- Из N случайных взять одно для изучения
- если невыученных меньше N - добить случайными выученными
...

Давай перенесем код из loadNotLearnedWords() обратно в startLearningMenu().

```Kotlin
 fun startLearningMenu() {
        while (true) {
            val hiddenWord = notLearnedWord.random()
            val wordListRestriction = 3

            if (notLearnedWord.size >= wordListRestriction) {
                fourNotLearnedWord = notLearnedWord.filterNot { it == hiddenWord }.shuffled().take(wordListRestriction).toMutableList()

            } else {
                repeat(wordListRestriction) {
                    fourNotLearnedWord.add(notLearnedWord[(0..notLearnedWord.lastIndex).random()])
                }
            }
            
            fourNotLearnedWord.add(hiddenWord)
            fourNotLearnedWord = fourNotLearnedWord.shuffled().toMutableList()
            
            // ....
```            

И вот снизим мутабельность и упростим логику в соответствии с алгоритмом.
При этом сократим область видимости мутабельных списков:

```Kotlin
 fun startLearningMenu() {
        while (true) {
            val wordListRestriction = 3
            val (hiddenWord: Word, fourNotLearnedWord: List<Word>) =
                notLearnedWord.shuffled().take(wordListRestriction)
                    .let { questionWords ->
                        val hiddenWord = questionWords.random()
                        val words = if (questionWords.size < wordListRestriction) {
                            val learnedWord = WordFile().dictionary
                                .filter { it.correctAnswersCount >= REPETITIONS_TO_MEMORIZE }
                            questionWords + learnedWord.shuffled()
                                .take(wordListRestriction - questionWords.size)
                        } else questionWords
                        hiddenWord to words
                    }

        //
        //   val hiddenWord = notLearnedWord.random()
        //   
        //
        //   if (notLearnedWord.size >= wordListRestriction) {
        //       fourNotLearnedWord =
        //           notLearnedWord.filterNot { it == hiddenWord }.shuffled().take(wordListRestriction).toMutableList()
        //
        //   } else {
        //       repeat(wordListRestriction) {
        //           fourNotLearnedWord.add(notLearnedWord[(0..notLearnedWord.lastIndex).random()])
        //       }
        //   }
        //
        //   fourNotLearnedWord.add(hiddenWord)
        //   fourNotLearnedWord = fourNotLearnedWord.shuffled().toMutableList()

```

Добавил в пример [деструктуризацию](https://kotlinlang.org/docs/destructuring-declarations.html), для расширения кругозора. Обычно я за легко читаемый код.

Итого: давай поправим 3, и пойдем дальше

2023-09-20 18:46 UTC, danelyan approved these changes
Отлично. Идем дальше )

2023-09-22 10:11 UTC, merged