lesson_6 ready
Gaileks/LearnEnglishWordsTelegramBot pull request #6
Opened 2023-10-19 08:45 UTC by Gaileks

2023-10-19 23:58 UTC, danelyan reviewed
Круто, проделал большую работу! Все же есть пара [corner cases](https://en.wikipedia.org/wiki/Corner_case).
Чтобы их словить, давай временно сделаем `learnedAnswerCount = 1` и урежем словарь:
```
hello|привет|0
dog|собака|0
cat|кошка|0
house|дом|0
```

### Проблема 1
Попробуй запустить в дебаг режиме, поставив точку останова в ConsoleMenu на 62 строку и временно замьютив точку: 
    <img width="80" alt="Screenshot 2023-10-20 at 02 49 41" src="https://github.com/Gaileks/LearnEnglishWordsTelegramBot/assets/7125622/cc5342f1-8623-4176-a7d1-3cd6ab4dbb95">

Пройди тест несколько раз, сбрасывая прогресс, но не выходя из приложения.
После нескольких повторов, включи точку останова и, как только она отработает, посмотри на стек вызовов:

<img width="350" alt="Screenshot 2023-10-20 at 02 54 00" src="https://github.com/Gaileks/LearnEnglishWordsTelegramBot/assets/7125622/05236986-2969-4aff-97f4-bcc705714d60">

Стектрейс копиться. Для нашего тренажера это может быть не критично, но представь что мы делаем приложение для банковского терминала, через какое-то время стек вызовов переполниться и приложение упадет. При этом ошибка может проявить себя значительно позже.

### Проблема 2 (хотя это скорее наблюдение)
Если посмотреть на словарь, можно заметить, что несколько оставшихся  невыученных слов могут долго не появляться:

```
hello|привет|0
dog|собака|3
cat|кошка|9
house|дом|5
```
Впрочем, это похоже на осознанное решение, чтобы не показывать одно невыученное слово несколько раз подряд, поэтому можно и так оставить

2023-10-20 00:08 UTC, danelyan requested changes

2023-10-20 00:08 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +            if (question != null) {
У нас же уже есть тут проверка на null для question, где-то тут и можно печатать что все слова выучены и делать брейк из цикла

2023-10-20 00:08 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +                    checkingLearnedWords()
Вот эта проверка кажется не нужна

2023-10-20 00:08 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        dictionary = loadDictionary()
Да, после сброса словаря закономерно требуется перезагрузить его из файла.

А давай вынесем конвертирование словаря в строку и сохранение в файл в один метод, задача которого будет - сохранение списка слов в файл.
А обнуление будем делать для словаря в цикле. Тогда не нужно перегружать словарь

2023-10-20 00:08 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +    private fun loadDictionary(): MutableList<Word> {
лучше стараться делать классы как можно более абстрактными, я бы сделал чтобы loadDictionary() возвращал `List<Word>`.

2023-10-20 00:08 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        wordFile.readLines().forEach {
Тут я бы заменил на mapNotNull, а после сплита строки доставал элементы получившегося списка через `line.getOrNull(0) ?: return@mapNotNull null`, ведь сейчас нет защиты от некорректных строк в words.txt

2023-10-21 11:33 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +            if (question != null) {
1 проблему не совсем понял, как решать.
2 да, такая логика ( взята из видео лекций), я раньше делал, что всегда предлагается невыученное слово.

2023-10-21 11:34 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        dictionary = loadDictionary()
Поменял, заодно поменял логику проверки слов

2023-10-21 11:37 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        wordFile.readLines().forEach {
Класс! поменял, протестировал, так действительно лучше

2023-10-21 11:38 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +    private fun loadDictionary(): MutableList<Word> {
Правило помню, что то пропустил тут , спасибо

2023-10-21 21:54 UTC, danelyan requested changes

2023-10-21 21:54 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +                    trainer.endProgram()
endProgram - не относится к тренажеру слов, это часть отвечающая скорее за ввод вывод. Тут просто можно делать exitProcess(0)

2023-10-21 21:54 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +    fun endProgram(): Nothing = exitProcess(0)
это я бы убрал отсюда, так как не имеет отношение к тренажеру

2023-10-21 21:54 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        Word(it.questionWord, it.translate, 0)
сохранение делал бы тут же, так как знать о том чем занимается LearnWordsTrainer для сброса словаря использующему классу не обязательно

2023-10-21 21:54 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +    wordFile.readLines().mapNotNull {
тут ты неправильно понял суть mapNotNull - это метод, который применяет лямбду к каждому элементу списка и возвращает финальный преобразованный список, отфлильтрованный от нулевых значений

2023-10-21 21:54 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        val wordFile = File("words.txt")
"words.txt" - можно вынести в конструктор LearnWordsTrainer

2023-10-21 21:54 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +                    question.variants.size + 2 -> consoleMenu.startTheMenu()
Вот ключевой момент - тут ты стартуешь startTheMenu(), который стартует  startLearningMenu() и опять можешь попасть сюда. То есть - для выхода из меню ты вместо return или break стартуешь еще одно меню

2023-10-21 21:54 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +        val consoleMenu = ConsoleMenu()
ты безконтрольно создаешь новые ConsoleMenu(). Сколько у тебя фактически меню в приложении? Должно быть одно, так зачем тебе много его экземпляров?

2023-10-24 03:41 UTC, danelyan requested changes
Последние правки

2023-10-24 03:41 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        exitProcess(0)
Решать о том, что из приложения пора выходить - это задача консольного тренажера, а не класса отвечающего за показ загрузку словаря и показ вопросов

2023-10-24 03:41 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        wordFile.readLines().mapNotNull { it ->
```Kotlin
        return File(wordFileName)
            .readLines()
            .mapNotNull { it ->
                val line = it.split("|").filter { it.isNotEmpty() }
                if (line.size == 3) {
                    Word(
                        line.getOrNull(0) ?: return@mapNotNull null,
                        line.getOrNull(1) ?: return@mapNotNull null,
                        line[2].toIntOrNull() ?: return@mapNotNull null
                    )
                } else null
            }
```

2023-10-24 03:41 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +        startTheMenu()
Этот вызов необходим? Попробуй удалить

2023-10-24 09:33 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/ConsoleMenu.kt
> +        startTheMenu()
Да, без него все ок
Задумался, вот для чего то я его туда ставил, тестировал, наверно логику поменял, но не подчистил код…

2023-10-24 09:34 UTC, Gaileks commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        wordFile.readLines().mapNotNull { it ->
Спасибо за интересный пример

2023-10-24 09:39 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/LearnWordsTrainer.kt
> +        wordFile.readLines().mapNotNull { it ->
основная идея в том что семейство экстеншенов map - возвращает результат своей работы

2023-10-24 09:39 UTC, danelyan approved these changes
Идеально. Идем дальше

2023-10-24 10:36 UTC, merged