lesson_9 ready
Gaileks/LearnEnglishWordsTelegramBot pull request #9
Opened 2023-11-06 16:53 UTC by Gaileks

2023-11-06 16:56 UTC, Gaileks commented
Не совсем по тз но я старался

2023-11-09 01:50 UTC, danelyan requested changes

2023-11-09 01:50 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/TelegramBotService.kt
> +                                "text": "${question.variants[0].translate}",
давай  будем формировать содержимое "inline_keyboard применяя mapIndexed, не завязываясь жестко на 4 элемента списка

2023-11-09 01:50 UTC, danelyan commented on Сoursework/LearnEnglishWordsTelegramBot/src/main/kotlin/Telegram.kt
> +                    telegramBotService.sendMessage(botToken, chatId, "Прогресс  обнулен!")
давай передавать botToken в TelegramBotService через конструктор

2023-11-14 11:34 UTC, danelyan approved these changes
Хорошо

2023-11-14 11:34 UTC, merged